version: "3.9"
services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    networks:
      - search
    restart: unless-stopped
    volumes:
      - search-data:/meili_data
    environment:
      MEILI_MASTER_KEY: test
    expose:
      - "7700"

  bot:
    build:
      context: "."
      dockerfile: bot/Dockerfile
    networks:
      - search
    env_file: .env
    environment:
      MEILISEARCH_URL: http://meilisearch:7700
      RUST_LOG: warn,xkcd_bot=info
    restart: unless-stopped

  indexer:
    build:
      context: "."
      dockerfile: indexer/Dockerfile
    networks:
      - search
    env_file: .env
    environment:
      MEILISEARCH_URL: http://meilisearch:7700
      RUST_LOG: warn,xkcd_indexer=info
    restart: unless-stopped

networks:
  search:

volumes:
  search-data:
